### ISSUE TITLE
Failed to activate the fitness package

### ISSUE THREAD

**Issue by mikeabney** [matt-schrader/FitnesseForAtom#1]
In Atom 1.0.0. Tried to run the toggle action and received the following stack trace:

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/mike/.atom/packages/fitnesse/lib/fitnesse-view.coffee:4:199)
    at /Users/mike/.atom/packages/fitnesse/lib/fitnesse-view.coffee:9:5
    at Object.<anonymous> (/Users/mike/.atom/packages/fitnesse/lib/fitnesse-view.coffee:52:5)
    at Object.<anonymous> (/Users/mike/.atom/packages/fitnesse/lib/fitnesse-view.coffee:54:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)

**Comment by matt-schrader** [comment]
Mike,

I apologize for this taking so long but I've resolved this issue.  Please
let me know if you run into anything else!

Thanks,

Matt

On Mon, Jun 29, 2015 at 2:33 PM, mikeabney notifications@github.com wrote:

> In Atom 1.0.0. Tried to run the toggle action and received the following
> stack trace:
> 
> TypeError: Cannot read property 'prototype' of undefined
> at __extends
> (/Users/mike/.atom/packages/fitnesse/lib/fitnesse-view.coffee:4:199)
> at /Users/mike/.atom/packages/fitnesse/lib/fitnesse-view.coffee:9:5
> at Object.
> (/Users/mike/.atom/packages/fitnesse/lib/fitnesse-view.coffee:52:5)
> at Object.
> (/Users/mike/.atom/packages/fitnesse/lib/fitnesse-view.coffee:54:4)
> at Module._compile (module.js:452:26)
> at Object.requireCoffeeScript
> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
> at Module.load (module.js:347:32)
> at Function.Module._load (module.js:302:12)
> at Module.require (module.js:357:17)
> at require (module.js:376:17)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matt-schrader/FitnesseForAtom/issues/1.

## 

Thank you,

Matt Schrader
(608) 931-7580
1249 Swallow Rd
Waukesha, WI 53189

**Comment by mikeabney** [comment]
No worries. I should be able to try it out in the next week or so. Thanks!
